# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-30 04:25
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Project', '0001_initial'),
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='MCPUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('github_username', models.CharField(blank=True, max_length=100, null=True)),
                ('slack_handle', models.CharField(blank=True, max_length=100, null=True)),
                ('github_oath', models.CharField(blank=True, max_length=100, null=True)),
                ('github_orgs', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='MCPUserProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project.Project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.MCPUser')),
            ],
        ),
        migrations.AddField(
            model_name='mcpuser',
            name='projects',
            field=models.ManyToManyField(through='Users.MCPUserProject', to='Project.Project'),
        ),
        migrations.AlterUniqueTogether(
            name='mcpuserproject',
            unique_together=set([('user', 'project')]),
        ),
    ]
