# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-06 21:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mcp.Processor.models
import mcp.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0001_initial'),
        ('Project', '0001_initial'),
        ('Resource', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=50)),
                ('target', models.CharField(max_length=50)),
                ('value_map', mcp.fields.MapField(blank=True, default={})),
                ('built_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('ran_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('reported_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('released_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('manual', models.BooleanField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('build', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='Project.Build')),
                ('commit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Project.Commit')),
                ('project', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='Project.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cookie', models.CharField(default=mcp.Processor.models.getCookie, max_length=36)),
                ('hostname', models.CharField(max_length=100)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('index', models.IntegerField(blank=True, null=True)),
                ('state', models.CharField(default='allocated', max_length=9,choices=[('allocated', 'allocated'), ('building', 'building'), ('built1', 'built1'), ('built', 'built'), ('releasing', 'releasing'), ('released1', 'released1'), ('released', 'released')])),
                ('message', models.CharField(default='', max_length=200, blank=True)),
                ('success', models.BooleanField(default=False)),
                ('package_files', mcp.fields.StringListField(blank=True, default=[])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('foundation_id', models.CharField(blank=True, max_length=100, null=True)),
                ('structure_id', models.CharField(blank=True, max_length=100, null=True)),
                ('buildjob', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Processor.BuildJob')),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Resource.NetworkResource')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Resource.Resource')),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_state', models.CharField(max_length=10)),
                ('to_state', models.CharField(max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PromotionBuild',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project.Build')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Processor.Promotion')),
            ],
        ),
        migrations.CreateModel(
            name='PromotionPkgVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packrat_id', models.CharField(max_length=100)),
                ('package_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project.PackageVersion')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Processor.Promotion')),
            ],
        ),
        migrations.CreateModel(
            name='QueueItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=50)),
                ('target', models.CharField(max_length=50)),
                ('priority', models.IntegerField(default=50)),
                ('manual', models.BooleanField()),
                ('resource_status_map', mcp.fields.MapField(blank=True, default={})),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('build', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='Project.Build')),
                ('commit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Project.Commit')),
                ('project', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='Project.Project')),
                ('promotion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Processor.Promotion')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='User.User')),
            ],
        ),
        migrations.AddField(
            model_name='promotion',
            name='package_versions',
            field=models.ManyToManyField(through='Processor.PromotionPkgVersion', to='Project.PackageVersion'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='status',
            field=models.ManyToManyField(through='Processor.PromotionBuild', to='Project.Build'),
        ),
        migrations.AddField(
            model_name='buildjob',
            name='promotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Processor.Promotion'),
        ),
        migrations.AddField(
            model_name='buildjob',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='User.User'),
        ),
        migrations.AlterUniqueTogether(
            name='promotionpkgversion',
            unique_together=set([('promotion', 'package_version')]),
        ),
        migrations.AlterUniqueTogether(
            name='promotionbuild',
            unique_together=set([('promotion', 'build')]),
        ),
    ]
