#!/usr/bin/env python3
import os

os.environ.setdefault( 'DJANGO_SETTINGS_MODULE', 'mcp.settings' )

import django
django.setup()

import time
import sys
from datetime import datetime, timezone

from mcp.Processor.models import BuildJob


job_id = sys.argv[1]

job = BuildJob.objects.get( pk=job_id )

if not job.built_at:
  print( 'Job "{0}" has not completed building'.format( job_id ) )
  sys.exit( 1 )

print( 'Setting job to Ran...' )
job.ran_at = datetime.now( timezone.utc )
job.full_clean()
job.save()

job = BuildJob.objects.get( pk=job_id )
while job.reported_at is None:
  print( 'Waiting for job to Report....' )
  time.sleep( 5 )
  job = BuildJob.objects.get( pk=job_id )

print( 'Setting job to Acknoledged....' )
job.acknowledged_at = datetime.now( timezone.utc )
job.full_clean()
job.save()
