#!/bin/bash

if [ $( id -u ) != 0 ];
then
  echo "Must be root"
  exit 1
fi

if [ -f /usr/local/mcp/setup/setupCompleted ];
then
  echo "The setup wizzard has allready be run..."
  echo "It is not safe to run setupWizard again."
  exit 1
fi

set -e
set -x

echo "Creating database..."
su postgres -c "echo \"CREATE ROLE mcp WITH PASSWORD 'mcp' NOSUPERUSER NOCREATEDB NOCREATEROLE LOGIN;\" | psql"
su postgres -c "createdb -O mcp mcp"

echo "Fixing cinp migrations..."  #when we are off precise this can go away
rm -fr /usr/lib/python2.7/dist-packages/cinp/migrations
mv /usr/lib/python2.7/dist-packages/cinp/migrations_south /usr/lib/python2.7/dist-packages/cinp/migrations

echo "Populating db..."
/usr/local/mcp/util/manage.py syncdb --noinput --database=mcp
/usr/local/mcp/util/manage.py syncdb --all --database=mcp
/usr/local/mcp/util/manage.py migrate --fake cinp --database=mcp
/usr/local/mcp/util/manage.py migrate --fake mcp.Users --database=mcp
/usr/local/mcp/util/manage.py migrate --fake mcp.Processor --database=mcp
/usr/local/mcp/util/manage.py migrate --fake mcp.Project --database=mcp
/usr/local/mcp/util/manage.py migrate --fake mcp.Resource --database=mcp

/usr/local/mcp/util/manage.py loaddata initial_data --database=mcp
/usr/local/mcp/util/manage.py loaddata initial_data --database=default

echo "Creating super user..."
/usr/local/mcp/util/manage.py createsuperuser --noinput --username=root --email=test@test.com --database=mcp

echo "Creating basic objects..."
/usr/local/mcp/setup/setupHelper.py

echo "Done!"
touch /usr/local/mcp/setup/setupCompleted
