#!/usr/bin/env python3
import os

os.environ.setdefault( "DJANGO_SETTINGS_MODULE", "mcp.settings" )

import sys
from datetime import datetime

from django.utils.timezone import utc
from mcp.Processor.models import BuildJob


job_id = sys.argv[1]

job = BuildJob.objects.get( pk=job_id )

if not job.reported_at:
  print( 'Job {0} not reported, can not acknowledge.'.format( job_id ) )
  sys.exit( 1 )

job.acknowledged_at = datetime.utcnow().replace( tzinfo=utc )
job.save()
