#!/usr/bin/python -u
import os

os.environ.setdefault( "DJANGO_SETTINGS_MODULE", "mcp.settings" )

import sys
from datetime import datetime

from django.utils.timezone import utc
from mcp.Processor.models import BuildJob


job_id = sys.argv[1]

job = BuildJob.objects.get( pk=job_id )

if not job.built_at:
  print 'Job "%s" has not completed building' % job_id
  sys.exit( 1 )

job.ran_at = datetime.utcnow().replace( tzinfo=utc )
job.reported_at = datetime.utcnow().replace( tzinfo=utc )
job.acknowledged_at = datetime.utcnow().replace( tzinfo=utc )
job.save()
