#!/usr/bin/python -u
import os
import time

os.environ.setdefault( "DJANGO_SETTINGS_MODULE", "mcp.settings" )

import sys
from datetime import datetime

from django.utils.timezone import utc
from mcp.Processor.models import BuildJob


job_id = sys.argv[1]

job = BuildJob.objects.get( pk=job_id )

if not job.built_at:
  print 'Job "%s" has not completed building' % job_id
  sys.exit( 1 )

print 'Setting job to Ran...'
job.ran_at = datetime.utcnow().replace( tzinfo=utc )
job.save()

job = BuildJob.objects.get( pk=job_id )
while job.reported_at is None:
  print 'Waiting for job to Report....'
  time.sleep( 5 )
  job = BuildJob.objects.get( pk=job_id )

print 'Setting job to Acknoledged....'
job.acknowledged_at = datetime.utcnow().replace( tzinfo=utc )
job.save()
