#!/usr/bin/python -u
import os

os.environ.setdefault( "DJANGO_SETTINGS_MODULE", "mcp.settings" )

import sys
import optparse

from mcp.Processor.models import QueueItem
from mcp.Projects.models import Build, Project
from mcp.Resources.models import ResourceGroup

oparser = optparse.OptionParser( description='Queue Job', usage='%prog [options]\n-b/--build and -t/--target are mutually exclusive, only one of the will process.' )

oparser.add_option( '-b', '--build', help='Pre-defined Build Name', dest='build' )
oparser.add_option( '-t', '--target', help='Target Name', dest='target' )

oparser.add_option( '-p', '--priority', help='Queue Item Priority (default: 50)', dest='priority', default=50 )
oparser.add_option( '-r', '--branch', help='git branch to check out (default: master)', dest='branch', default='master' )

oparser.add_option( '-m', '--manual', help='Flag as Manual Build (-b only), ie: manual -> no auto cleanup (default: False)', dest='manual', default=False, action='store_true' )

oparser.add_option( '-d', '--distro', help='Submit Task on Sepecified Distro (-t only)', dest='distro' )
oparser.add_option( '-p', '--git', help='Git URL (URL to the local copy) (-t only)', dest='git' )

oparser.add_option( '-e', '--resource-group', help='Resource Group to use (can be specified multiple times)', dest='resource_group', default=[], action='append' )

( options, args ) = oparser.parse_args()

if options.build:
  try:
    build = Build.objects.get( pk=options.build )
  except Build.DoesNotExist:
    print 'Build "%s" not Found' % options.build
    sys.exit( 1 )

  item = QueueItem.inQueueBuild( build, options.branch, options.manual, options.priority )

elif options.target:
  if not options.distro or not options.git:
    print 'distro and git are required for target'
    sys.exit( 1 )

  try:
    project = Project.objects.get( pk=options.project )
  except Project.DoesNotExist:
    print 'Project "%s" not found' % options.project
    sys.exit( 1 )

  item = QueueItem.inQueueTarget( project, options.branch, options.distro, options.target, options.priority )

else:
  oparser.print_help()
  sys.exit( 1 )

group_list = []
for name in options.resource_group:
  try:
    group = ResourceGroup.objects.get( name=name )
  except ResourceGroup.DoesNotExist:
    print 'Resource Group "%s" not found'
    item.delete()
    sys.exit( 1 )

  group_list.append( group )

item.resource_groups = group_list
item.save()

print 'Item "%s" Queued' % item
sys.exit( 0 )
