#!/bin/sh

set -x
set -e

if [ -e /var/run/mcpIterate.lock ];
then
  echo "Iterate lock exists, bailing"
  exit 1
fi

touch /var/run/mcpIterate.lock

# get packages up to date
/usr/local/mcp/cron/tron

# get the latest from git
/usr/local/mcp/cron/rinzler

# check the commits
/usr/local/mcp/cron/recognizer

# run thoes jobs
/usr/local/mcp/cron/sark

# update the dependancy graph
/usr/local/mcp/util/graph | dot -Tpng -o/var/www/mcp/static/graph.png
/usr/local/mcp/util/graph | dot -Tpdf -o/var/www/mcp/static/graph.pdf

rm /var/run/mcpIterate.lock
exit 0
