#!/bin/sh

set -x
set -e

if [ -e /var/run/mcpIterate.lock ];
then
  echo "Iterate lock exists, bailing"
  exit 1
fi

touch /var/run/mcpIterate.lock

# get packages up to date
./tron

# get the latest from git
./rinzler

# check the commits
./recognizer

# run thoes jobs
./sark

# update the dependancy graph
cd ../util
./dograph
cd ../cron

rm /var/run/mcpIterate.lock
exit 0
