#!/bin/sh

set -x
set -e

if [ -e /var/run/mcpIterate.lock ];
then
  echo "Iterate lock exists, bailing"
  exit 1
fi

touch /var/run/mcpIterate.lock

# check the commits
/usr/local/mcp/cron/recognizer

# run thoes jobs
/usr/local/mcp/cron/sark

rm /var/run/mcpIterate.lock
exit 0
