#!/bin/sh

set -x
set -e

if [ -e /var/run/mcpIterate.lock ];
then
  echo "Iterate lock exists, bailing"
  exit 1
fi

touch /var/run/mcpIterate.lock

# check the commits
./recognizer

# run thoes jobs
./sark

rm /var/run/mcpIterate.lock
exit 0
