#!/bin/bash

set -e

if [ "x$1" == "xi" ]
then
  set -x
  ARGS=""
else
  ARGS="-c"
fi

if [ -e /var/run/mcpIterate.lock ];
then
  echo "Iterate lock exists, bailing"
  exit 1
fi

touch /var/run/mcpIterate.lock

# check the commits
/usr/local/mcp/cron/recognizer $ARGS

# run thoes jobs
/usr/local/mcp/cron/sark $ARGS

rm /var/run/mcpIterate.lock
exit 0
