# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-07-07 18:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mcp.fields

BUILD_AHEAD_COUNT = { 'small': { 'ubuntu-xenial': 4, 'ubuntu-bionic': 4 } }


def load_sites( app, schema_editor ):
  Site = app.get_model( 'Resource', 'Site' )

  site = Site( name='site1' )
  site.domain = 'site1.test'
  site.full_clean()
  site.save()


def load_resources( app, schema_editor ):
  StructureResource = app.get_model( 'Resource', 'StructureResource' )
  Site = app.get_model( 'Resource', 'Site' )

  site = Site.objects.get( name='site1' )

  for size in ( 'small', 'medium' ):
    for name in ( 'ubuntu-trusty', 'ubuntu-xenial', 'ubuntu-bionic', 'centos-6', 'centos-7', 'esx' ):
      dr = StructureResource( name='{0}-{1}'.format( name, size ) )
      dr.description = '{0} of {1}'.format( name.capitalize(), size.capitalize() )
      dr.blueprint = 'mcp-{0}'.format( name )
      # dr.complex = 'esx'
      dr.complex = 'vca'
      dr.site = site
      try:
        dr.build_ahead_count = BUILD_AHEAD_COUNT[ size ][ name ]
      except KeyError:
        dr.build_ahead_count = 2

      dr.full_clean()
      dr.save()

  dr = StructureResource( name='vmware-esx' )
  dr.description = 'Vmware ESX'
  dr.blueprint = 'mcp-vmware-esx'
  # dr.complex = 'esx'
  dr.complex = 'vca'
  dr.site = site
  dr.build_ahead_count = 0
  dr.full_clean()
  dr.save()

  dr = StructureResource( name='vmware-vca' )
  dr.description = 'Vmware VCenter Appliance'
  dr.blueprint = 'mcp-vmware-vca'
  # dr.complex = 'esx'
  dr.complex = 'vca'
  dr.site = site
  dr.build_ahead_count = 0
  dr.full_clean()
  dr.save()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Network',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('contractor_addressblock_id', models.IntegerField(unique=True)),
                ('contractor_network_name', models.CharField(max_length=40)),
                ('monalythic', models.BooleanField(default=True)),
                ('size', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('key', models.CharField(editable=False, max_length=250, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResourceInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contractor_structure_id', models.IntegerField(unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('name', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DynamicResource',
            fields=[
                ('resource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Resource.Resource')),
                ('build_ahead_count', models.IntegerField(default=0)),
                ('blueprint_id', models.CharField(max_length=40)),
                ('complex_id', models.CharField(max_length=40)),
            ],
            bases=('Resource.resource',),
        ),
        migrations.CreateModel(
            name='DynamicResourceInstance',
            fields=[
                ('resourceinstance_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Resource.ResourceInstance')),
                ('contractor_foundation_id', models.CharField(max_length=100)),
                ('interface_map', mcp.fields.MapField(default={})),
                ('dynamic_resource', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Resource.DynamicResource')),
            ],
            bases=('Resource.resourceinstance',),
        ),
        migrations.CreateModel(
            name='StaticResource',
            fields=[
                ('resource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Resource.Resource')),
                ('group_name', models.CharField(max_length=50)),
                ('interface_map', mcp.fields.MapField(default={})),
            ],
            bases=('Resource.resource',),
        ),
        migrations.CreateModel(
            name='StaticResourceInstance',
            fields=[
                ('resourceinstance_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Resource.ResourceInstance')),
                ('static_resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Resource.StaticResource')),
            ],
            bases=('Resource.resourceinstance',),
        ),
        migrations.AddField(
            model_name='resource',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Resource.Site'),
        ),
        migrations.AddField(
            model_name='network',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Resource.Site'),
        ),
        migrations.AlterUniqueTogether(
            name='resource',
            unique_together=set([('name', 'site')]),
        ),
        migrations.RunPython( load_sites ),
        migrations.RunPython( load_resources ),
    ]
