# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-30 04:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

BUILD_AHEAD_COUNT = { 'small': { 'xenail': 4 } }


def load_resources( app, schema_editor ):
  VMResource = app.get_model( 'Resource', 'VMResource' )

  for size in ( 'small', 'medium' ):
    for name in ( 'trusty', 'precise', 'xenial', 'centos6' ):
      vm = VMResource( name='{0}-generic-{1}'.format( size, name ) )
      vm.description = '{0} Generic {1}'.format( size.capitalize(), name.capitalize() )
      vm.blueprint = '{0}-mcp'.format( name )
      vm.vm_template = '{0}-generic'.format( size )
      try:
        vm.build_ahead_count = BUILD_AHEAD_COUNT[ size ][ name ]
      except KeyError:
        vm.build_ahead_count = 2

      vm.full_clean()
      vm.save()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkResource',
            fields=[
                ('subnet', models.IntegerField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
                ('blueprint', models.CharField(max_length=40)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResourceGroup',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
                ('_config_list', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='HardwareResource',
            fields=[
                ('resource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Resource.Resource')),
                ('hardware_template', models.CharField(max_length=50)),
            ],
            bases=('Resource.resource',),
        ),
        migrations.CreateModel(
            name='VMResource',
            fields=[
                ('resource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Resource.Resource')),
                ('vm_template', models.CharField(max_length=50)),
                ('build_ahead_count', models.IntegerField(default=0)),
            ],
            bases=('Resource.resource',),
        ),
        migrations.RunPython( load_resources ),
    ]
