#!/bin/bash

set -e

if [ "x$1" == "xi" ]
then
  set -x
  ARGS=""
else
  ARGS="-c"
  #  give fullIterate a chance to take presidence, sence the cron starts both at the same time
  sleep 5
fi

if [ -e /var/run/mcpIterate.lock ];
then
  if [ "x$1" == "xi" ]
  then
    echo "Iterate lock exists, bailing"
  fi
  exit 1
fi

touch /var/run/mcpIterate.lock

# check the commits
/usr/lib/mcp/cron/recognizer $ARGS

# run thoes jobs
/usr/lib/mcp/cron/sark $ARGS

rm /var/run/mcpIterate.lock
exit 0
